title: phpdbg

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-mentions

# Just The Docs config
search_enabled: true
aux_links:
    "View on GitHub":
      - "//github.com/rmccue/phpdbg-docs"

# Force default layout
defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
